version: "2.0"
services:
    apache:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./src:/var/www/
        links:
            - mysql
        networks:
            - default
    mysql:
        image: mysql:5.7
        ports: 
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: "America/Sao_Paulo"
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent: