version: "3.1"
services:
    apache:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./src/www:/var/www/html/
        links:
            - mysql
        networks:
            - default
    mysql:
        image: mysql:5.7
        ports: 
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default

volumes:
  persistent:
